; generated by PrusaSlicer 2.9.6 on 2026-09-28 at 03:47:31 UTC

; 

; external perimeters extrusion width = 1.00mm
; perimeters extrusion width = 1.00mm
; infill extrusion width = 1.00mm
; solid infill extrusion width = 1.00mm
; top infill extrusion width = 1.00mm
; first layer extrusion width = 1.00mm

;TYPE:Custom
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0 ; reset extrusion distance
; Filament gcode
M107 ; disable fan
;LAYER_CHANGE
;Z:0.5
;HEIGHT:0.5
G92 E0 ; reset extrusion distance
G1 X26.5 Y17.3 F7800 ; move to first layer point
G1 Z.5 ; move to first layer point
;TYPE:External perimeter
;WIDTH:1
G1 F1800
G1 X35.7 Y17.3 E1.70725 ; perimeter
G1 X35.7 Y21.5 E2.48665 ; perimeter
G1 X26.5 Y21.5 E4.1939 ; perimeter
G1 X26.5 Y17.42 E4.95103 ; perimeter
G92 E0 ; reset extrusion distance
G1 X27.242 Y20.588 F7800 ; move to first infill point
;TYPE:Solid infill
;WIDTH:1.2166
G1 F1800
G1 X27.144 Y20.686 E.03196 ; infill
G1 X27.18 Y20.82 E.06396 ; infill
G1 X27.314 Y20.856 E.09596 ; infill
G1 X27.412 Y20.758 E.12792 ; infill
G1 X27.376 Y20.624 E.15992 ; infill
;WIDTH:1
G1 X27.17 Y19.198 E.42729 ; infill
G1 X28.802 Y20.83 E.85559 ; infill
G1 X30.064 Y20.83 E1.08978 ; infill
G1 X27.203 Y17.97 E1.84048 ; infill
G1 X28.466 Y17.97 E2.07486 ; infill
G1 X31.327 Y20.83 E2.82556 ; infill
G1 X32.589 Y20.83 E3.05975 ; infill
G1 X29.728 Y17.97 E3.81045 ; infill
G1 X30.991 Y17.97 E4.04483 ; infill
G1 X33.852 Y20.83 E4.79553 ; infill
G1 X35.368 Y21.168 E5.08376 ; infill
;WIDTH:0.787301
G1 X35.154 Y21.177 E5.11404 ; infill
;WIDTH:0.829841
G1 X35.13 Y21.091 E5.12745 ; infill
;WIDTH:0.872381
G1 X35.105 Y21.005 E5.14169 ; infill
;WIDTH:0.91492
G1 X35.08 Y20.919 E5.15673 ; infill
;WIDTH:0.95746
G1 X35.055 Y20.833 E5.17256 ; infill
;WIDTH:1
G1 X35.03 Y20.747 E5.18918 ; infill
G1 X32.253 Y17.97 E5.91797 ; infill
G1 X33.516 Y17.97 E6.15235 ; infill
G1 X35.03 Y19.484 E6.54968 ; infill
G1 X35.049 Y17.951 E6.83418 ; infill
;WIDTH:1.14784
G1 X35.082 Y18.077 E6.86235 ; infill
G1 X34.99 Y18.169 E6.89049 ; infill
G1 X34.865 Y18.135 E6.91851 ; infill
G1 X34.831 Y18.01 E6.94653 ; infill
G1 X34.923 Y17.918 E6.97467 ; infill
G92 E0 ; reset extrusion distance
G1 X12.554 Y18.355 F7800 ; move to first perimeter point
;TYPE:External perimeter
;WIDTH:1
G1 F1800
G1 X12.413 Y18.47 E.03376 ; perimeter
G1 X12.254 Y18.5 E.06379 ; perimeter
G1 X5.946 Y18.5 E1.23437 ; perimeter
G1 X5.769 Y18.463 E1.26793 ; perimeter
G1 X5.631 Y18.369 E1.29892 ; perimeter
G1 X5.5 Y18.118 E1.35146 ; perimeter
G1 X5.5 Y11.746 E2.53392 ; perimeter
G1 X5.534 Y11.575 E2.56627 ; perimeter
G1 X5.623 Y11.439 E2.59643 ; perimeter
G1 X5.868 Y11.3 E2.6487 ; perimeter
G1 X12.254 Y11.3 E3.83375 ; perimeter
G1 X12.442 Y11.342 E3.8695 ; perimeter
G1 X12.586 Y11.449 E3.90279 ; perimeter
G1 X12.7 Y11.661 E3.94746 ; perimeter
G1 X12.7 Y18.054 E5.13381 ; perimeter
G1 X12.637 Y18.272 E5.17592 ; perimeter
G92 E0 ; reset extrusion distance
G1 X17.7 Y21.5 F7800 ; move to first perimeter point
G1 F1800
G1 X2.5 Y21.5 E2.82067 ; perimeter
G1 X2.5 Y4.3 E6.01248 ; perimeter
G1 X17.7 Y4.3 E8.83315 ; perimeter
G1 X17.7 Y21.38 E12.0027 ; perimeter
G92 E0 ; reset extrusion distance
G1 X17.432 Y17.545 F7800 ; move to first infill point
;TYPE:Internal infill
;WIDTH:1
G1 F1800
G1 X13.37 Y13.482 E1.06615 ; infill
G1 X13.37 Y18.07 E1.91755 ; infill
G1 X13.323 Y18.379 E1.97555 ; infill
G1 X13.201 Y18.647 E2.03019 ; infill
G1 X12.98 Y18.904 E2.09309 ; infill
G1 X12.667 Y19.091 E2.16075 ; infill
G1 X14.406 Y20.83 E2.61713 ; infill
G1 X8.093 Y20.83 E3.78864 ; infill
G1 X6.433 Y19.17 E4.22428 ; infill
G1 X5.923 Y19.17 E4.31892 ; infill
G1 X5.503 Y19.082 E4.39855 ; infill
G1 X5.154 Y18.846 E4.47673 ; infill
G1 X4.923 Y18.505 E4.55316 ; infill
G1 X4.847 Y18.25 E4.60254 ; infill
G1 X4.83 Y17.567 E4.72932 ; infill
G1 X3.17 Y15.907 E5.16496 ; infill
G1 X3.17 Y9.594 E6.33647 ; infill
G1 X4.909 Y11.333 E6.79285 ; infill
G1 X5.134 Y10.976 E6.87116 ; infill
G1 X5.418 Y10.761 E6.93726 ; infill
G1 X5.698 Y10.657 E6.99269 ; infill
G1 X10.518 Y10.63 E7.88715 ; infill
G1 X4.857 Y4.97 E9.37267 ; infill
G1 X11.17 Y4.97 E10.54418 ; infill
G1 X17.432 Y11.232 E12.18756 ; infill
G92 E0 ; reset extrusion distance
M107 ; disable fan
;TYPE:Custom
; Filament-specific end gcode 
;END gcode for filament
; objects_info = {"objects":[]}
; filament used [mm] = 41.29
; filament used [cm3] = 0.10
; total filament used [g] = 0.00
; total filament cost = 0.00
; total filament used for wipe tower [g] = 0.00
; estimated printing time (normal mode) = 9s
; estimated first layer printing time (normal mode) = 9s

; prusaslicer_config = begin
; arc_fitting = disabled
; autoemit_temperature_commands = 1
; automatic_extrusion_widths = 0
; automatic_infill_combination = 0
; automatic_infill_combination_max_layer_height = 100%
; avoid_crossing_curled_overhangs = 0
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_shape = -60x-125,60x-125,60x125,-60x125
; bed_temperature = 0
; bed_temperature_extruder = 0
; before_layer_gcode = 
; between_objects_gcode = 
; binary_gcode = 0
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 0
; bottom_solid_min_thickness = 0
; bridge_acceleration = 0
; bridge_angle = 0
; bridge_fan_speed = 0
; bridge_flow_ratio = 1
; bridge_speed = 60
; brim_separation = 0
; brim_type = outer_only
; brim_width = 0
; chamber_minimal_temperature = 0
; chamber_temperature = 0
; color_change_gcode = M600
; colorprint_heights = 
; complete_objects = 0
; cooling = 0
; cooling_perimeter_transition_distance = 0
; cooling_slowdown_logic = uniform_cooling
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; custom_parameters_filament = ""
; custom_parameters_print = 
; custom_parameters_printer = 
; default_acceleration = 0
; deretract_speed = 0
; disable_fan_first_layers = 3
; dont_support_bridges = 1
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0
; enable_dynamic_fan_speeds = 0
; enable_dynamic_overhang_speeds = 0
; end_filament_gcode = "; Filament-specific end gcode \n;END gcode for filament\n"
; end_gcode = 
; ensure_vertical_shell_thickness = enabled
; external_perimeter_acceleration = 0
; external_perimeter_extrusion_width = 0
; external_perimeter_speed = 50%
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 1
; extra_perimeters_on_overhangs = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 1
; fan_always_on = 0
; fan_below_layer_time = 60
; filament_abrasive = 0
; filament_colour = #29B2B2
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 0
; filament_density = 0
; filament_diameter = 1.75
; filament_flush_speed = 0
; filament_flush_volume = 0
; filament_infill_max_crossing_speed = 0
; filament_infill_max_speed = 0
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 0
; filament_minimal_purge_on_wipe_tower = 15
; filament_multitool_ramming = 0
; filament_multitool_ramming_flow = 10
; filament_multitool_ramming_volume = 10
; filament_notes = ""
; filament_purge_multiplier = 100%
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_seam_gap_distance = 15%
; filament_settings_id = ""
; filament_shrinkage_compensation_xy = 0%
; filament_shrinkage_compensation_z = 0%
; filament_soluble = 0
; filament_spool_weight = 0
; filament_stamping_distance = 0
; filament_stamping_loading_speed = 20
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; fill_angle = 45
; fill_density = 20%
; fill_pattern = rectilinear
; first_layer_acceleration = 0
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 0
; first_layer_extrusion_width = 1
; first_layer_height = 0.5
; first_layer_infill_speed = 0
; first_layer_speed = 30
; first_layer_speed_over_raft = 30
; first_layer_temperature = 0
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 20
; gcode_comments = 1
; gcode_flavor = reprapfirmware
; gcode_label_objects = disabled
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; idle_temperature = nil
; infill_acceleration = 0
; infill_anchor = 600%
; infill_anchor_max = 50
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0
; infill_first = 0
; infill_overlap = 25%
; infill_speed = 80
; interface_shells = 0
; interlocking_beam = 0
; interlocking_beam_layer_count = 2
; interlocking_beam_width = 0.8
; interlocking_boundary_avoidance = 2
; interlocking_depth = 2
; interlocking_orientation = 22.5
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = 
; layer_height = 0.5
; machine_limits_usage = time_estimate_only
; machine_max_acceleration_e = 10000,5000
; machine_max_acceleration_extruding = 1500,1250
; machine_max_acceleration_retracting = 1500,1250
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 9000,1000
; machine_max_acceleration_y = 9000,1000
; machine_max_acceleration_z = 500,200
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 500,200
; machine_max_feedrate_y = 500,200
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 2.5,2.5
; machine_max_jerk_x = 10,10
; machine_max_jerk_y = 10,10
; machine_max_jerk_z = 0.2,0.4
; machine_max_junction_deviation = 0,0
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 0
; max_layer_height = 0
; max_print_height = 200
; max_print_speed = 80
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_bead_width = 85%
; min_fan_speed = 0
; min_feature_size = 25%
; min_layer_height = 0.07
; min_print_speed = 10
; min_skirt_length = 0
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; multimaterial_purging = 140
; notes = 
; nozzle_diameter = 0.8
; nozzle_high_flow = 0
; only_one_perimeter_first_layer = 0
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; over_bridge_speed = 0
; overhang_fan_speed_0 = 0
; overhang_fan_speed_1 = 0
; overhang_fan_speed_2 = 0
; overhang_fan_speed_3 = 0
; overhang_speed_0 = 15
; overhang_speed_1 = 15
; overhang_speed_2 = 20
; overhang_speed_3 = 25
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 0
; perimeter_extruder = 1
; perimeter_extrusion_width = 0
; perimeter_generator = arachne
; perimeter_speed = 60
; perimeters = 1
; physical_printer_settings_id = 
; post_process = 
; prefer_clockwise_movements = 0
; print_settings_id = 
; printer_model = 
; printer_notes = 
; printer_settings_id = 
; printer_technology = FFF
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 0
; resolution = 0
; retract_before_travel = 2
; retract_before_wipe = 0%
; retract_layer_change = 0
; retract_length = 0
; retract_length_toolchange = 10
; retract_lift = 0
; retract_lift_above = 0
; retract_lift_below = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 40
; scarf_seam_entire_loop = 0
; scarf_seam_length = 20
; scarf_seam_max_segment_length = 1
; scarf_seam_on_inner_perimeters = 0
; scarf_seam_only_on_smooth = 1
; scarf_seam_placement = nowhere
; scarf_seam_start_height = 0%
; seam_gap_distance = 15%
; seam_position = aligned
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_distance = 6
; skirt_height = 1
; skirts = 0
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 5
; small_perimeter_speed = 15
; solid_infill_acceleration = 0
; solid_infill_below_area = 70
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0
; solid_infill_speed = 20
; spiral_vase = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_filament_gcode = "; Filament gcode\n"
; start_gcode = 
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = -1
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 1
; support_material_interface_layers = 3
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 2.5
; support_material_speed = 60
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 0
; support_material_with_sheath = 1
; support_material_xy_spacing = 50%
; support_tree_angle = 40
; support_tree_angle_slow = 25
; support_tree_branch_diameter = 2
; support_tree_branch_diameter_angle = 5
; support_tree_branch_diameter_double_wall = 3
; support_tree_branch_distance = 1
; support_tree_tip_diameter = 0.8
; support_tree_top_rate = 15%
; temperature = 0
; template_custom_gcode = 
; thick_bridges = 1
; thin_walls = 1
; thumbnails = 
; thumbnails_format = PNG
; toolchange_gcode = 
; toolchange_ordering = optimized
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0
; top_one_perimeter_type = none
; top_solid_infill_acceleration = 0
; top_solid_infill_speed = 15
; top_solid_layers = 0
; top_solid_min_thickness = 0
; travel_acceleration = 0
; travel_lift_before_obstacle = 0
; travel_max_lift = 0
; travel_ramping_lift = 0
; travel_short_distance_acceleration = 0
; travel_slope = 0
; travel_speed = 130
; travel_speed_z = 0
; use_firmware_retraction = 0
; use_relative_e_distances = 0
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_distribution_count = 1
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 0
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_acceleration = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_cone_angle = 0
; wipe_tower_extra_flow = 100%
; wipe_tower_extra_spacing = 100%
; wipe_tower_extruder = 0
; wipe_tower_no_sparse_layers = 0
; wipe_tower_width = 60
; wiping_volumes_matrix = 0,140,140,140,140,140,0,140,140,140,140,140,0,140,140,140,140,140,0,140,140,140,140,140,0
; wiping_volumes_use_custom_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
